// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: workloadapi/federatedservice.proto

package workloadapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceScope int32

const (
	ServiceScope_GLOBAL ServiceScope = 0
	// GLOBAL_ONLY is deprecated. Use GLOBAL with takeover=true instead.
	//
	// Deprecated: Marked as deprecated in workloadapi/federatedservice.proto.
	ServiceScope_GLOBAL_ONLY ServiceScope = 1
	// SEGMENT indicates the service is visible only within its segment
	ServiceScope_SEGMENT ServiceScope = 2
)

// Enum value maps for ServiceScope.
var (
	ServiceScope_name = map[int32]string{
		0: "GLOBAL",
		1: "GLOBAL_ONLY",
		2: "SEGMENT",
	}
	ServiceScope_value = map[string]int32{
		"GLOBAL":      0,
		"GLOBAL_ONLY": 1,
		"SEGMENT":     2,
	}
)

func (x ServiceScope) Enum() *ServiceScope {
	p := new(ServiceScope)
	*p = x
	return p
}

func (x ServiceScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceScope) Descriptor() protoreflect.EnumDescriptor {
	return file_workloadapi_federatedservice_proto_enumTypes[0].Descriptor()
}

func (ServiceScope) Type() protoreflect.EnumType {
	return &file_workloadapi_federatedservice_proto_enumTypes[0]
}

func (x ServiceScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceScope.Descriptor instead.
func (ServiceScope) EnumDescriptor() ([]byte, []int) {
	return file_workloadapi_federatedservice_proto_rawDescGZIP(), []int{0}
}

// Segment allows this cluster to tell peers its own segment and domain.
// Peers will use this to build domains for global services.
// Peers must have a Segment resource in their own cluster with a matching name and domain,
// otherwide we will not peer resources.
type Segment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the segment (globally)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// domain suffix for the segment (in the view of this cluster)
	Domain        string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_workloadapi_federatedservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_workloadapi_federatedservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_workloadapi_federatedservice_proto_rawDescGZIP(), []int{0}
}

func (x *Segment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Segment) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type FederatedService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name represents the name for the service.
	// For Kubernetes, this is the Service name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace represents the namespace for the service.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Hostname represents the FQDN of the service.
	// For Kubernetes, this would be <name>.<namespace>.svc.<cluster domain>.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// TrafficDistribution within the source cluster if any.
	TrafficDistribution string `protobuf:"bytes,8,opt,name=traffic_distribution,json=trafficDistribution,proto3" json:"traffic_distribution,omitempty"`
	// List of subject alt names to verify against. This will aggregate the SANs of all workloads in
	// the remote cluster.
	SubjectAltNames []string `protobuf:"bytes,4,rep,name=subject_alt_names,json=subjectAltNames,proto3" json:"subject_alt_names,omitempty"`
	// Ports for the service.
	// The target_port may be overridden on a per-workload basis.
	Ports []*Port `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	// Capacity for this service. This represents a logical weighting for amount of traffic the service can handle.
	// A value of 0 is valid, and indicates the service is unable to handle any traffic.
	// Other arbitrary values are valid, and control the relative amount of traffic that the service can handle (relative to other object's capacity).
	// If unset, the capacity is default to 1.
	Capacity *wrapperspb.UInt32Value `protobuf:"bytes,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Information about a remote waypoint, if any
	Waypoint *RemoteWaypoint `protobuf:"bytes,7,opt,name=waypoint,proto3" json:"waypoint,omitempty"`
	// WaypointFor is specified only if the Service itself is a waypoint.
	WaypointFor string `protobuf:"bytes,9,opt,name=waypoint_for,json=waypointFor,proto3" json:"waypoint_for,omitempty"`
	// ProtocolsByPort maps service port numbers to their protocols (e.g., 80 -> "HTTP", 443 -> "HTTPS")
	ProtocolsByPort map[uint32]string `protobuf:"bytes,10,rep,name=protocols_by_port,json=protocolsByPort,proto3" json:"protocols_by_port,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ServiceScope indicates the scope of this service (global, global_only, etc.)
	Scope ServiceScope `protobuf:"varint,11,opt,name=scope,proto3,enum=istio.workload.ServiceScope" json:"scope,omitempty"`
	// Takeover indicates whether this service should override the standard *.cluster.local addresses.
	// When true, peered services will be accessible via the cluster.local domain.
	// Deprecated: GLOBAL_ONLY scope (scope=GLOBAL_ONLY) implies takeover=true for backwards compatibility.
	Takeover bool `protobuf:"varint,12,opt,name=takeover,proto3" json:"takeover,omitempty"`
	// IngressUseWaypoint specifies whether ingress gateways should use the waypoint for this service.
	IngressUseWaypoint *wrapperspb.BoolValue `protobuf:"bytes,13,opt,name=ingress_use_waypoint,json=ingressUseWaypoint,proto3" json:"ingress_use_waypoint,omitempty"`
	// The amount of traffic that should be drained from this workload. valid values: [0-100]
	DrainingWeight *wrapperspb.UInt32Value `protobuf:"bytes,14,opt,name=draining_weight,json=drainingWeight,proto3" json:"draining_weight,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FederatedService) Reset() {
	*x = FederatedService{}
	mi := &file_workloadapi_federatedservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederatedService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederatedService) ProtoMessage() {}

func (x *FederatedService) ProtoReflect() protoreflect.Message {
	mi := &file_workloadapi_federatedservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederatedService.ProtoReflect.Descriptor instead.
func (*FederatedService) Descriptor() ([]byte, []int) {
	return file_workloadapi_federatedservice_proto_rawDescGZIP(), []int{1}
}

func (x *FederatedService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FederatedService) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *FederatedService) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *FederatedService) GetTrafficDistribution() string {
	if x != nil {
		return x.TrafficDistribution
	}
	return ""
}

func (x *FederatedService) GetSubjectAltNames() []string {
	if x != nil {
		return x.SubjectAltNames
	}
	return nil
}

func (x *FederatedService) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *FederatedService) GetCapacity() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *FederatedService) GetWaypoint() *RemoteWaypoint {
	if x != nil {
		return x.Waypoint
	}
	return nil
}

func (x *FederatedService) GetWaypointFor() string {
	if x != nil {
		return x.WaypointFor
	}
	return ""
}

func (x *FederatedService) GetProtocolsByPort() map[uint32]string {
	if x != nil {
		return x.ProtocolsByPort
	}
	return nil
}

func (x *FederatedService) GetScope() ServiceScope {
	if x != nil {
		return x.Scope
	}
	return ServiceScope_GLOBAL
}

func (x *FederatedService) GetTakeover() bool {
	if x != nil {
		return x.Takeover
	}
	return false
}

func (x *FederatedService) GetIngressUseWaypoint() *wrapperspb.BoolValue {
	if x != nil {
		return x.IngressUseWaypoint
	}
	return nil
}

func (x *FederatedService) GetDrainingWeight() *wrapperspb.UInt32Value {
	if x != nil {
		return x.DrainingWeight
	}
	return nil
}

type RemoteWaypoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name represents the name for the service.
	// This will reference the name of another FederatedService.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Name represents the namespace for the service.
	// This will reference the namespace of another FederatedService.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteWaypoint) Reset() {
	*x = RemoteWaypoint{}
	mi := &file_workloadapi_federatedservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteWaypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteWaypoint) ProtoMessage() {}

func (x *RemoteWaypoint) ProtoReflect() protoreflect.Message {
	mi := &file_workloadapi_federatedservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteWaypoint.ProtoReflect.Descriptor instead.
func (*RemoteWaypoint) Descriptor() ([]byte, []int) {
	return file_workloadapi_federatedservice_proto_rawDescGZIP(), []int{2}
}

func (x *RemoteWaypoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoteWaypoint) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_workloadapi_federatedservice_proto protoreflect.FileDescriptor

const file_workloadapi_federatedservice_proto_rawDesc = "" +
	"\n" +
	"\"workloadapi/federatedservice.proto\x12\x0eistio.workload\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1aworkloadapi/workload.proto\"5\n" +
	"\aSegment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"\x90\x06\n" +
	"\x10FederatedService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x121\n" +
	"\x14traffic_distribution\x18\b \x01(\tR\x13trafficDistribution\x12*\n" +
	"\x11subject_alt_names\x18\x04 \x03(\tR\x0fsubjectAltNames\x12*\n" +
	"\x05ports\x18\x05 \x03(\v2\x14.istio.workload.PortR\x05ports\x128\n" +
	"\bcapacity\x18\x06 \x01(\v2\x1c.google.protobuf.UInt32ValueR\bcapacity\x12:\n" +
	"\bwaypoint\x18\a \x01(\v2\x1e.istio.workload.RemoteWaypointR\bwaypoint\x12!\n" +
	"\fwaypoint_for\x18\t \x01(\tR\vwaypointFor\x12a\n" +
	"\x11protocols_by_port\x18\n" +
	" \x03(\v25.istio.workload.FederatedService.ProtocolsByPortEntryR\x0fprotocolsByPort\x122\n" +
	"\x05scope\x18\v \x01(\x0e2\x1c.istio.workload.ServiceScopeR\x05scope\x12\x1a\n" +
	"\btakeover\x18\f \x01(\bR\btakeover\x12L\n" +
	"\x14ingress_use_waypoint\x18\r \x01(\v2\x1a.google.protobuf.BoolValueR\x12ingressUseWaypoint\x12E\n" +
	"\x0fdraining_weight\x18\x0e \x01(\v2\x1c.google.protobuf.UInt32ValueR\x0edrainingWeight\x1aB\n" +
	"\x14ProtocolsByPortEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x0eRemoteWaypoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace*<\n" +
	"\fServiceScope\x12\n" +
	"\n" +
	"\x06GLOBAL\x10\x00\x12\x13\n" +
	"\vGLOBAL_ONLY\x10\x01\x1a\x02\b\x01\x12\v\n" +
	"\aSEGMENT\x10\x02B\x11Z\x0fpkg/workloadapib\x06proto3"

var (
	file_workloadapi_federatedservice_proto_rawDescOnce sync.Once
	file_workloadapi_federatedservice_proto_rawDescData []byte
)

func file_workloadapi_federatedservice_proto_rawDescGZIP() []byte {
	file_workloadapi_federatedservice_proto_rawDescOnce.Do(func() {
		file_workloadapi_federatedservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workloadapi_federatedservice_proto_rawDesc), len(file_workloadapi_federatedservice_proto_rawDesc)))
	})
	return file_workloadapi_federatedservice_proto_rawDescData
}

var file_workloadapi_federatedservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workloadapi_federatedservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_workloadapi_federatedservice_proto_goTypes = []any{
	(ServiceScope)(0),              // 0: istio.workload.ServiceScope
	(*Segment)(nil),                // 1: istio.workload.Segment
	(*FederatedService)(nil),       // 2: istio.workload.FederatedService
	(*RemoteWaypoint)(nil),         // 3: istio.workload.RemoteWaypoint
	nil,                            // 4: istio.workload.FederatedService.ProtocolsByPortEntry
	(*Port)(nil),                   // 5: istio.workload.Port
	(*wrapperspb.UInt32Value)(nil), // 6: google.protobuf.UInt32Value
	(*wrapperspb.BoolValue)(nil),   // 7: google.protobuf.BoolValue
}
var file_workloadapi_federatedservice_proto_depIdxs = []int32{
	5, // 0: istio.workload.FederatedService.ports:type_name -> istio.workload.Port
	6, // 1: istio.workload.FederatedService.capacity:type_name -> google.protobuf.UInt32Value
	3, // 2: istio.workload.FederatedService.waypoint:type_name -> istio.workload.RemoteWaypoint
	4, // 3: istio.workload.FederatedService.protocols_by_port:type_name -> istio.workload.FederatedService.ProtocolsByPortEntry
	0, // 4: istio.workload.FederatedService.scope:type_name -> istio.workload.ServiceScope
	7, // 5: istio.workload.FederatedService.ingress_use_waypoint:type_name -> google.protobuf.BoolValue
	6, // 6: istio.workload.FederatedService.draining_weight:type_name -> google.protobuf.UInt32Value
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_workloadapi_federatedservice_proto_init() }
func file_workloadapi_federatedservice_proto_init() {
	if File_workloadapi_federatedservice_proto != nil {
		return
	}
	file_workloadapi_workload_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workloadapi_federatedservice_proto_rawDesc), len(file_workloadapi_federatedservice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workloadapi_federatedservice_proto_goTypes,
		DependencyIndexes: file_workloadapi_federatedservice_proto_depIdxs,
		EnumInfos:         file_workloadapi_federatedservice_proto_enumTypes,
		MessageInfos:      file_workloadapi_federatedservice_proto_msgTypes,
	}.Build()
	File_workloadapi_federatedservice_proto = out.File
	file_workloadapi_federatedservice_proto_goTypes = nil
	file_workloadapi_federatedservice_proto_depIdxs = nil
}
