// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: workloadapi/federatedservice.proto

package workloadapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FederatedService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name represents the name for the service.
	// For Kubernetes, this is the Service name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace represents the namespace for the service.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Hostname represents the FQDN of the service.
	// For Kubernetes, this would be <name>.<namespace>.svc.<cluster domain>.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// TrafficDistribution within the source cluster if any.
	TrafficDistribution string `protobuf:"bytes,8,opt,name=traffic_distribution,json=trafficDistribution,proto3" json:"traffic_distribution,omitempty"`
	// List of subject alt names to verify against. This will aggregate the SANs of all workloads in
	// the remote cluster.
	SubjectAltNames []string `protobuf:"bytes,4,rep,name=subject_alt_names,json=subjectAltNames,proto3" json:"subject_alt_names,omitempty"`
	// Ports for the service.
	// The target_port may be overridden on a per-workload basis.
	Ports []*Port `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	// Capacity for this service. This represents a logical weighting for amount of traffic the service can handle.
	// A value of 0 is valid, and indicates the service is unable to handle any traffic.
	// Other arbitrary values are valid, and control the relative amount of traffic that the service can handle (relative to other object's capacity).
	// If unset, the capacity is default to 1.
	Capacity *wrapperspb.UInt32Value `protobuf:"bytes,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Information about a remote waypoint, if any
	Waypoint *RemoteWaypoint `protobuf:"bytes,7,opt,name=waypoint,proto3" json:"waypoint,omitempty"`
	// WaypointFor is specified only if the Service itself is a waypoint.
	WaypointFor   string `protobuf:"bytes,9,opt,name=waypoint_for,json=waypointFor,proto3" json:"waypoint_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederatedService) Reset() {
	*x = FederatedService{}
	mi := &file_workloadapi_federatedservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederatedService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederatedService) ProtoMessage() {}

func (x *FederatedService) ProtoReflect() protoreflect.Message {
	mi := &file_workloadapi_federatedservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederatedService.ProtoReflect.Descriptor instead.
func (*FederatedService) Descriptor() ([]byte, []int) {
	return file_workloadapi_federatedservice_proto_rawDescGZIP(), []int{0}
}

func (x *FederatedService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FederatedService) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *FederatedService) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *FederatedService) GetTrafficDistribution() string {
	if x != nil {
		return x.TrafficDistribution
	}
	return ""
}

func (x *FederatedService) GetSubjectAltNames() []string {
	if x != nil {
		return x.SubjectAltNames
	}
	return nil
}

func (x *FederatedService) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *FederatedService) GetCapacity() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *FederatedService) GetWaypoint() *RemoteWaypoint {
	if x != nil {
		return x.Waypoint
	}
	return nil
}

func (x *FederatedService) GetWaypointFor() string {
	if x != nil {
		return x.WaypointFor
	}
	return ""
}

type RemoteWaypoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name represents the name for the service.
	// This will reference the name of another FederatedService.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Name represents the namespace for the service.
	// This will reference the namespace of another FederatedService.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteWaypoint) Reset() {
	*x = RemoteWaypoint{}
	mi := &file_workloadapi_federatedservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteWaypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteWaypoint) ProtoMessage() {}

func (x *RemoteWaypoint) ProtoReflect() protoreflect.Message {
	mi := &file_workloadapi_federatedservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteWaypoint.ProtoReflect.Descriptor instead.
func (*RemoteWaypoint) Descriptor() ([]byte, []int) {
	return file_workloadapi_federatedservice_proto_rawDescGZIP(), []int{1}
}

func (x *RemoteWaypoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoteWaypoint) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_workloadapi_federatedservice_proto protoreflect.FileDescriptor

const file_workloadapi_federatedservice_proto_rawDesc = "" +
	"\n" +
	"\"workloadapi/federatedservice.proto\x12\x0eistio.workload\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1aworkloadapi/workload.proto\"\x84\x03\n" +
	"\x10FederatedService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x121\n" +
	"\x14traffic_distribution\x18\b \x01(\tR\x13trafficDistribution\x12*\n" +
	"\x11subject_alt_names\x18\x04 \x03(\tR\x0fsubjectAltNames\x12*\n" +
	"\x05ports\x18\x05 \x03(\v2\x14.istio.workload.PortR\x05ports\x128\n" +
	"\bcapacity\x18\x06 \x01(\v2\x1c.google.protobuf.UInt32ValueR\bcapacity\x12:\n" +
	"\bwaypoint\x18\a \x01(\v2\x1e.istio.workload.RemoteWaypointR\bwaypoint\x12!\n" +
	"\fwaypoint_for\x18\t \x01(\tR\vwaypointFor\"B\n" +
	"\x0eRemoteWaypoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespaceB\x11Z\x0fpkg/workloadapib\x06proto3"

var (
	file_workloadapi_federatedservice_proto_rawDescOnce sync.Once
	file_workloadapi_federatedservice_proto_rawDescData []byte
)

func file_workloadapi_federatedservice_proto_rawDescGZIP() []byte {
	file_workloadapi_federatedservice_proto_rawDescOnce.Do(func() {
		file_workloadapi_federatedservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workloadapi_federatedservice_proto_rawDesc), len(file_workloadapi_federatedservice_proto_rawDesc)))
	})
	return file_workloadapi_federatedservice_proto_rawDescData
}

var file_workloadapi_federatedservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workloadapi_federatedservice_proto_goTypes = []any{
	(*FederatedService)(nil),       // 0: istio.workload.FederatedService
	(*RemoteWaypoint)(nil),         // 1: istio.workload.RemoteWaypoint
	(*Port)(nil),                   // 2: istio.workload.Port
	(*wrapperspb.UInt32Value)(nil), // 3: google.protobuf.UInt32Value
}
var file_workloadapi_federatedservice_proto_depIdxs = []int32{
	2, // 0: istio.workload.FederatedService.ports:type_name -> istio.workload.Port
	3, // 1: istio.workload.FederatedService.capacity:type_name -> google.protobuf.UInt32Value
	1, // 2: istio.workload.FederatedService.waypoint:type_name -> istio.workload.RemoteWaypoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_workloadapi_federatedservice_proto_init() }
func file_workloadapi_federatedservice_proto_init() {
	if File_workloadapi_federatedservice_proto != nil {
		return
	}
	file_workloadapi_workload_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workloadapi_federatedservice_proto_rawDesc), len(file_workloadapi_federatedservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workloadapi_federatedservice_proto_goTypes,
		DependencyIndexes: file_workloadapi_federatedservice_proto_depIdxs,
		MessageInfos:      file_workloadapi_federatedservice_proto_msgTypes,
	}.Build()
	File_workloadapi_federatedservice_proto = out.File
	file_workloadapi_federatedservice_proto_goTypes = nil
	file_workloadapi_federatedservice_proto_depIdxs = nil
}
