// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package workloadapi

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Segment
func (this *Segment) MarshalJSON() ([]byte, error) {
	str, err := FederatedserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Segment
func (this *Segment) UnmarshalJSON(b []byte) error {
	return FederatedserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for FederatedService
func (this *FederatedService) MarshalJSON() ([]byte, error) {
	str, err := FederatedserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for FederatedService
func (this *FederatedService) UnmarshalJSON(b []byte) error {
	return FederatedserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RemoteWaypoint
func (this *RemoteWaypoint) MarshalJSON() ([]byte, error) {
	str, err := FederatedserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RemoteWaypoint
func (this *RemoteWaypoint) UnmarshalJSON(b []byte) error {
	return FederatedserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	FederatedserviceMarshaler   = &jsonpb.Marshaler{}
	FederatedserviceUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
