// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package workloadapi

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for SoloServiceExtension
func (this *SoloServiceExtension) MarshalJSON() ([]byte, error) {
	str, err := SoloMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SoloServiceExtension
func (this *SoloServiceExtension) UnmarshalJSON(b []byte) error {
	return SoloUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SoloWorkloadExtension
func (this *SoloWorkloadExtension) MarshalJSON() ([]byte, error) {
	str, err := SoloMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SoloWorkloadExtension
func (this *SoloWorkloadExtension) UnmarshalJSON(b []byte) error {
	return SoloUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	SoloMarshaler   = &jsonpb.Marshaler{}
	SoloUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
