// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: workloadapi/solo.proto

package workloadapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SoloServiceExtension are internal extension points (optionally) added to Service objects
type SoloServiceExtension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The service is configured with ingress-use-waypoint
	IngressUseWaypoint *wrapperspb.BoolValue `protobuf:"bytes,1,opt,name=ingress_use_waypoint,json=ingressUseWaypoint,proto3" json:"ingress_use_waypoint,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SoloServiceExtension) Reset() {
	*x = SoloServiceExtension{}
	mi := &file_workloadapi_solo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoloServiceExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoloServiceExtension) ProtoMessage() {}

func (x *SoloServiceExtension) ProtoReflect() protoreflect.Message {
	mi := &file_workloadapi_solo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoloServiceExtension.ProtoReflect.Descriptor instead.
func (*SoloServiceExtension) Descriptor() ([]byte, []int) {
	return file_workloadapi_solo_proto_rawDescGZIP(), []int{0}
}

func (x *SoloServiceExtension) GetIngressUseWaypoint() *wrapperspb.BoolValue {
	if x != nil {
		return x.IngressUseWaypoint
	}
	return nil
}

// SoloServiceExtension are internal extension points (optionally) added to Workload objects
type SoloWorkloadExtension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoloWorkloadExtension) Reset() {
	*x = SoloWorkloadExtension{}
	mi := &file_workloadapi_solo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoloWorkloadExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoloWorkloadExtension) ProtoMessage() {}

func (x *SoloWorkloadExtension) ProtoReflect() protoreflect.Message {
	mi := &file_workloadapi_solo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoloWorkloadExtension.ProtoReflect.Descriptor instead.
func (*SoloWorkloadExtension) Descriptor() ([]byte, []int) {
	return file_workloadapi_solo_proto_rawDescGZIP(), []int{1}
}

var File_workloadapi_solo_proto protoreflect.FileDescriptor

const file_workloadapi_solo_proto_rawDesc = "" +
	"\n" +
	"\x16workloadapi/solo.proto\x12\x0eistio.workload\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/wrappers.proto\"d\n" +
	"\x14SoloServiceExtension\x12L\n" +
	"\x14ingress_use_waypoint\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\x12ingressUseWaypoint\"\x17\n" +
	"\x15SoloWorkloadExtensionB\x11Z\x0fpkg/workloadapib\x06proto3"

var (
	file_workloadapi_solo_proto_rawDescOnce sync.Once
	file_workloadapi_solo_proto_rawDescData []byte
)

func file_workloadapi_solo_proto_rawDescGZIP() []byte {
	file_workloadapi_solo_proto_rawDescOnce.Do(func() {
		file_workloadapi_solo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workloadapi_solo_proto_rawDesc), len(file_workloadapi_solo_proto_rawDesc)))
	})
	return file_workloadapi_solo_proto_rawDescData
}

var file_workloadapi_solo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workloadapi_solo_proto_goTypes = []any{
	(*SoloServiceExtension)(nil),  // 0: istio.workload.SoloServiceExtension
	(*SoloWorkloadExtension)(nil), // 1: istio.workload.SoloWorkloadExtension
	(*wrapperspb.BoolValue)(nil),  // 2: google.protobuf.BoolValue
}
var file_workloadapi_solo_proto_depIdxs = []int32{
	2, // 0: istio.workload.SoloServiceExtension.ingress_use_waypoint:type_name -> google.protobuf.BoolValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workloadapi_solo_proto_init() }
func file_workloadapi_solo_proto_init() {
	if File_workloadapi_solo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workloadapi_solo_proto_rawDesc), len(file_workloadapi_solo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workloadapi_solo_proto_goTypes,
		DependencyIndexes: file_workloadapi_solo_proto_depIdxs,
		MessageInfos:      file_workloadapi_solo_proto_msgTypes,
	}.Build()
	File_workloadapi_solo_proto = out.File
	file_workloadapi_solo_proto_goTypes = nil
	file_workloadapi_solo_proto_depIdxs = nil
}
