//go:build vtprotobuf
// +build vtprotobuf

// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.1-0.20250313105119-ba97887b0a25
// source: workloadapi/solo.proto

package workloadapi

import (
	protohelpers "github.com/planetscale/vtprotobuf/protohelpers"
	wrapperspb "github.com/planetscale/vtprotobuf/types/known/wrapperspb"
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (this *SoloServiceExtension) EqualVT(that *SoloServiceExtension) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !(*wrapperspb.BoolValue)(this.IngressUseWaypoint).EqualVT((*wrapperspb.BoolValue)(that.IngressUseWaypoint)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *SoloServiceExtension) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*SoloServiceExtension)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *SoloWorkloadExtension) EqualVT(that *SoloWorkloadExtension) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !(*wrapperspb.UInt32Value)(this.DrainingWeight).EqualVT((*wrapperspb.UInt32Value)(that.DrainingWeight)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *SoloWorkloadExtension) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*SoloWorkloadExtension)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (m *SoloServiceExtension) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SoloServiceExtension) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *SoloServiceExtension) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.IngressUseWaypoint != nil {
		size, err := (*wrapperspb.BoolValue)(m.IngressUseWaypoint).MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SoloWorkloadExtension) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SoloWorkloadExtension) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *SoloWorkloadExtension) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.DrainingWeight != nil {
		size, err := (*wrapperspb.UInt32Value)(m.DrainingWeight).MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SoloServiceExtension) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IngressUseWaypoint != nil {
		l = (*wrapperspb.BoolValue)(m.IngressUseWaypoint).SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *SoloWorkloadExtension) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DrainingWeight != nil {
		l = (*wrapperspb.UInt32Value)(m.DrainingWeight).SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}
