apiVersion: release-notes/v2

kind: bug-fix

area: traffic-management

issue:
  - https://github.com/solo-io/istio/issues/3380

releaseNotes:
- |
  **Fixed** with flat networking, traffic would not traverse remote-only waypoints
