apiVersion: release-notes/v2

kind: feature

area: traffic-management

issue:
  - https://github.com/solo-io/istio/issues/2797

releaseNotes:
- |
  **Added** multicluster support to ECS platform discovery.
  
