// Copyright Solo.io, Inc
//
// Licensed under a Solo commercial license, not Apache License, Version 2 or any other variant

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	scheme "istio.io/istio/soloapi/client/clientset/versioned/scheme"
	soloapiv1alpha1 "istio.io/istio/soloapi/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SegmentsGetter has a method to return a SegmentInterface.
// A group's client should implement this interface.
type SegmentsGetter interface {
	Segments(namespace string) SegmentInterface
}

// SegmentInterface has methods to work with Segment resources.
type SegmentInterface interface {
	Create(ctx context.Context, segment *soloapiv1alpha1.Segment, opts v1.CreateOptions) (*soloapiv1alpha1.Segment, error)
	Update(ctx context.Context, segment *soloapiv1alpha1.Segment, opts v1.UpdateOptions) (*soloapiv1alpha1.Segment, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, segment *soloapiv1alpha1.Segment, opts v1.UpdateOptions) (*soloapiv1alpha1.Segment, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*soloapiv1alpha1.Segment, error)
	List(ctx context.Context, opts v1.ListOptions) (*soloapiv1alpha1.SegmentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *soloapiv1alpha1.Segment, err error)
	SegmentExpansion
}

// segments implements SegmentInterface
type segments struct {
	*gentype.ClientWithList[*soloapiv1alpha1.Segment, *soloapiv1alpha1.SegmentList]
}

// newSegments returns a Segments
func newSegments(c *AdminV1alpha1Client, namespace string) *segments {
	return &segments{
		gentype.NewClientWithList[*soloapiv1alpha1.Segment, *soloapiv1alpha1.SegmentList](
			"segments",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *soloapiv1alpha1.Segment { return &soloapiv1alpha1.Segment{} },
			func() *soloapiv1alpha1.SegmentList { return &soloapiv1alpha1.SegmentList{} },
		),
	}
}
