// Copyright Solo.io, Inc
//
// Licensed under a Solo commercial license, not Apache License, Version 2 or any other variant

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	scheme "istio.io/istio/soloapi/client/clientset/versioned/scheme"
	soloapiv1alpha1 "istio.io/istio/soloapi/v1alpha1"
	rest "k8s.io/client-go/rest"
)

type AdminV1alpha1Interface interface {
	RESTClient() rest.Interface
	SegmentsGetter
}

// AdminV1alpha1Client is used to interact with features provided by the admin.solo.io group.
type AdminV1alpha1Client struct {
	restClient rest.Interface
}

func (c *AdminV1alpha1Client) Segments(namespace string) SegmentInterface {
	return newSegments(c, namespace)
}

// NewForConfig creates a new AdminV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*AdminV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new AdminV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*AdminV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &AdminV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new AdminV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *AdminV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new AdminV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *AdminV1alpha1Client {
	return &AdminV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := soloapiv1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *AdminV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
