{{if .Values.load }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pilot-load
  namespace: {{.Release.Namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilot-load
  namespace: {{.Release.Namespace}}
  labels:
    app: pilot-load
spec:
  replicas: 1
  template:
    metadata:
      name: pilot-load
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8765"
        checksum/config: {{ include (print $.Template.BasePath "/pilot-load-config.yaml") . | sha256sum }}
      labels:
        sidecar.istio.io/inject: "false"
        app: pilot-load
    spec:
      # May take a while to shut down
      terminationGracePeriodSeconds: 2000
      serviceAccountName: pilot-load
      containers:
        - name: pilot-load
          image: howardjohn/pilot-load
          args:
            - "cluster"
            - "--pilot-address=istiod.{{.Release.Namespace}}:15010"
            - "--config=/etc/config/config/config.yaml"
            - --cluster-type=fake-node
            - "--qps=5000"
          env:
            - name: KUBECONFIG
              value: /var/run/secrets/remote/kubeconfig.yaml
          resources:
{{/*            requests:*/}}
{{/*              cpu: 4000m*/}}
{{/*              memory: 4Gi*/}}
          volumeMounts:
            - mountPath: /var/run/secrets/remote
              name: istio-kubeconfig
              readOnly: true
            - name: config
              mountPath: /etc/config/config
      volumes:
        - name: config
          configMap:
            name: pilot-load-config
        - name: istio-kubeconfig
          configMap:
            name: istio-kubeconfig
  selector:
    matchLabels:
      app: pilot-load
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pilot-load-{{.Release.Namespace}}
  namespace: {{.Release.Namespace}}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list", "create", "patch", "update", "delete"]
  - apiGroups: ["config.istio.io", "security.istio.io", "networking.istio.io", "authentication.istio.io", "rbac.istio.io", "telemetry.istio.io"]
    verbs: ["get", "watch", "list", "create", "patch", "update", "delete"]
    resources: ["*"]
  - apiGroups: ["coordination.k8s.io"]
    verbs: ["get", "watch", "list", "create", "patch", "update", "delete"]
    resources: ["*"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pilot-load-{{.Release.Namespace}}
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pilot-load
subjects:
  - kind: ServiceAccount
    name: pilot-load
    namespace: {{.Release.Namespace}}
{{ end }}
