// Copyright Solo.io, Inc
//
// Licensed under a Solo commercial license, not Apache License, Version 2 or any other variant

// Code generated by client-gen. DO NOT EDIT.

// Package fake has the automatically generated clients.
package fake
