// Copyright Solo.io, Inc
//
// Licensed under a Solo commercial license, not Apache License, Version 2 or any other variant

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "istio.io/istio/soloapi/client/clientset/versioned/typed/soloapi/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAdminV1alpha1 struct {
	*testing.Fake
}

func (c *FakeAdminV1alpha1) Segments(namespace string) v1alpha1.SegmentInterface {
	return newFakeSegments(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAdminV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
