// Copyright Solo.io, Inc
//
// Licensed under a Solo commercial license, not Apache License, Version 2 or any other variant

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	soloapiv1alpha1 "istio.io/istio/soloapi/client/clientset/versioned/typed/soloapi/v1alpha1"
	v1alpha1 "istio.io/istio/soloapi/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSegments implements SegmentInterface
type fakeSegments struct {
	*gentype.FakeClientWithList[*v1alpha1.Segment, *v1alpha1.SegmentList]
	Fake *FakeAdminV1alpha1
}

func newFakeSegments(fake *FakeAdminV1alpha1, namespace string) soloapiv1alpha1.SegmentInterface {
	return &fakeSegments{
		gentype.NewFakeClientWithList[*v1alpha1.Segment, *v1alpha1.SegmentList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("segments"),
			v1alpha1.SchemeGroupVersion.WithKind("Segment"),
			func() *v1alpha1.Segment { return &v1alpha1.Segment{} },
			func() *v1alpha1.SegmentList { return &v1alpha1.SegmentList{} },
			func(dst, src *v1alpha1.SegmentList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SegmentList) []*v1alpha1.Segment { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.SegmentList, items []*v1alpha1.Segment) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
