// Copyright Solo.io, Inc
//
// Licensed under a Solo commercial license, not Apache License, Version 2 or any other variant

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SegmentListerExpansion allows custom methods to be added to
// SegmentLister.
type SegmentListerExpansion interface{}

// SegmentNamespaceListerExpansion allows custom methods to be added to
// SegmentNamespaceLister.
type SegmentNamespaceListerExpansion interface{}
