// Copyright Solo.io, Inc
//
// Licensed under a Solo commercial license, not Apache License, Version 2 or any other variant

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	soloapiv1alpha1 "istio.io/istio/soloapi/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SegmentLister helps list Segments.
// All objects returned here must be treated as read-only.
type SegmentLister interface {
	// List lists all Segments in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*soloapiv1alpha1.Segment, err error)
	// Segments returns an object that can list and get Segments.
	Segments(namespace string) SegmentNamespaceLister
	SegmentListerExpansion
}

// segmentLister implements the SegmentLister interface.
type segmentLister struct {
	listers.ResourceIndexer[*soloapiv1alpha1.Segment]
}

// NewSegmentLister returns a new SegmentLister.
func NewSegmentLister(indexer cache.Indexer) SegmentLister {
	return &segmentLister{listers.New[*soloapiv1alpha1.Segment](indexer, soloapiv1alpha1.Resource("segment"))}
}

// Segments returns an object that can list and get Segments.
func (s *segmentLister) Segments(namespace string) SegmentNamespaceLister {
	return segmentNamespaceLister{listers.NewNamespaced[*soloapiv1alpha1.Segment](s.ResourceIndexer, namespace)}
}

// SegmentNamespaceLister helps list and get Segments.
// All objects returned here must be treated as read-only.
type SegmentNamespaceLister interface {
	// List lists all Segments in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*soloapiv1alpha1.Segment, err error)
	// Get retrieves the Segment from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*soloapiv1alpha1.Segment, error)
	SegmentNamespaceListerExpansion
}

// segmentNamespaceLister implements the SegmentNamespaceLister
// interface.
type segmentNamespaceLister struct {
	listers.ResourceIndexer[*soloapiv1alpha1.Segment]
}
