// Copyright Solo.io, Inc
//
// Licensed under a Solo commercial license, not Apache License, Version 2 or any other variant

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	versioned "istio.io/istio/soloapi/client/clientset/versioned"
	internalinterfaces "istio.io/istio/soloapi/client/informers/externalversions/internalinterfaces"
	soloapiv1alpha1 "istio.io/istio/soloapi/client/listers/soloapi/v1alpha1"
	istiosoloapiv1alpha1 "istio.io/istio/soloapi/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SegmentInformer provides access to a shared informer and lister for
// Segments.
type SegmentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() soloapiv1alpha1.SegmentLister
}

type segmentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSegmentInformer constructs a new informer for Segment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSegmentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSegmentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSegmentInformer constructs a new informer for Segment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSegmentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AdminV1alpha1().Segments(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AdminV1alpha1().Segments(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AdminV1alpha1().Segments(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AdminV1alpha1().Segments(namespace).Watch(ctx, options)
			},
		},
		&istiosoloapiv1alpha1.Segment{},
		resyncPeriod,
		indexers,
	)
}

func (f *segmentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSegmentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *segmentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&istiosoloapiv1alpha1.Segment{}, f.defaultInformer)
}

func (f *segmentInformer) Lister() soloapiv1alpha1.SegmentLister {
	return soloapiv1alpha1.NewSegmentLister(f.Informer().GetIndexer())
}
